using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ApartamentosRenta.Migrations
{
    /// <inheritdoc />
    public partial class StampSealContracts : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            if (migrationBuilder.ActiveProvider == "Npgsql.EntityFrameworkCore.PostgreSQL")
            {
                migrationBuilder.Sql("""
                    CREATE TABLE IF NOT EXISTS "StampSealContracts" (
                        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "PropiedadId" integer NOT NULL REFERENCES "Propiedades"("Id") ON DELETE CASCADE,
                        "Title" character varying(200) NOT NULL,
                        "Subtitle" character varying(200) NOT NULL,
                        "NoticeHtml" character varying(4000) NOT NULL,
                        "BodyHtml" text NOT NULL,
                        "UpdatedAt" timestamp with time zone NOT NULL
                    );

                    CREATE UNIQUE INDEX IF NOT EXISTS "IX_StampSealContracts_PropiedadId" ON "StampSealContracts" ("PropiedadId");

                    CREATE TABLE IF NOT EXISTS "StampSealSubmissions" (
                        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "PropiedadId" integer NOT NULL REFERENCES "Propiedades"("Id") ON DELETE CASCADE,
                        "ClientName" character varying(120) NOT NULL,
                        "ClientEmail" character varying(256) NOT NULL,
                        "ClientPhone" character varying(30) NULL,
                        "SubmissionType" integer NOT NULL,
                        "SignatureImageData" bytea NULL,
                        "SignatureImageContentType" character varying(100) NULL,
                        "ProposedChanges" character varying(4000) NULL,
                        "SubmittedAt" timestamp with time zone NOT NULL
                    );

                    CREATE INDEX IF NOT EXISTS "IX_StampSealSubmissions_PropiedadId" ON "StampSealSubmissions" ("PropiedadId");
                    CREATE INDEX IF NOT EXISTS "IX_StampSealSubmissions_SubmissionType" ON "StampSealSubmissions" ("SubmissionType");
                    CREATE INDEX IF NOT EXISTS "IX_StampSealSubmissions_SubmittedAt" ON "StampSealSubmissions" ("SubmittedAt");
                    """);
                return;
            }

            migrationBuilder.CreateTable(
                name: "StampSealContracts",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    PropiedadId = table.Column<int>(type: "INTEGER", nullable: false),
                    Title = table.Column<string>(type: "TEXT", maxLength: 200, nullable: false),
                    Subtitle = table.Column<string>(type: "TEXT", maxLength: 200, nullable: false),
                    NoticeHtml = table.Column<string>(type: "TEXT", maxLength: 4000, nullable: false),
                    BodyHtml = table.Column<string>(type: "TEXT", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_StampSealContracts", x => x.Id);
                    table.ForeignKey(
                        name: "FK_StampSealContracts_Propiedades_PropiedadId",
                        column: x => x.PropiedadId,
                        principalTable: "Propiedades",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "StampSealSubmissions",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    PropiedadId = table.Column<int>(type: "INTEGER", nullable: false),
                    ClientName = table.Column<string>(type: "TEXT", maxLength: 120, nullable: false),
                    ClientEmail = table.Column<string>(type: "TEXT", maxLength: 256, nullable: false),
                    ClientPhone = table.Column<string>(type: "TEXT", maxLength: 30, nullable: true),
                    SubmissionType = table.Column<int>(type: "INTEGER", nullable: false),
                    SignatureImageData = table.Column<byte[]>(type: "BLOB", nullable: true),
                    SignatureImageContentType = table.Column<string>(type: "TEXT", maxLength: 100, nullable: true),
                    ProposedChanges = table.Column<string>(type: "TEXT", maxLength: 4000, nullable: true),
                    SubmittedAt = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_StampSealSubmissions", x => x.Id);
                    table.ForeignKey(
                        name: "FK_StampSealSubmissions_Propiedades_PropiedadId",
                        column: x => x.PropiedadId,
                        principalTable: "Propiedades",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_StampSealContracts_PropiedadId",
                table: "StampSealContracts",
                column: "PropiedadId",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_StampSealSubmissions_PropiedadId",
                table: "StampSealSubmissions",
                column: "PropiedadId");

            migrationBuilder.CreateIndex(
                name: "IX_StampSealSubmissions_SubmissionType",
                table: "StampSealSubmissions",
                column: "SubmissionType");

            migrationBuilder.CreateIndex(
                name: "IX_StampSealSubmissions_SubmittedAt",
                table: "StampSealSubmissions",
                column: "SubmittedAt");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "StampSealContracts");

            migrationBuilder.DropTable(
                name: "StampSealSubmissions");
        }
    }
}
