using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ApartamentosRenta.Migrations
{
    /// <inheritdoc />
    public partial class FixLeaseContractPostgresIdentity : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            if (migrationBuilder.ActiveProvider is not "Npgsql.EntityFrameworkCore.PostgreSQL")
            {
                return;
            }

            migrationBuilder.Sql("""
                DO $ef$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1
                        FROM pg_attribute a
                        JOIN pg_class c ON c.oid = a.attrelid
                        JOIN pg_namespace n ON n.oid = c.relnamespace
                        WHERE n.nspname = 'public'
                          AND c.relname = 'LeaseContracts'
                          AND a.attname = 'Id'
                          AND a.attidentity IN ('a', 'd')
                    ) THEN
                        ALTER TABLE "LeaseContracts"
                            ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;
                    END IF;
                END
                $ef$;

                SELECT setval(
                    pg_get_serial_sequence('"LeaseContracts"', 'Id'),
                    GREATEST(COALESCE((SELECT MAX("Id") FROM "LeaseContracts"), 0), 1),
                    (SELECT COUNT(*) > 0 FROM "LeaseContracts")
                );
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
        }
    }
}
