using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ApartamentosRenta.Migrations
{
    /// <inheritdoc />
    public partial class FixReservaPaymentSettingsIdentity : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            if (migrationBuilder.ActiveProvider != "Npgsql.EntityFrameworkCore.PostgreSQL")
            {
                return;
            }

            // Original CREATE used "Id integer PRIMARY KEY" without IDENTITY, so inserts for
            // azul/pingui failed on Render. Make Id identity and advance the sequence.
            migrationBuilder.Sql("""
                DO $$
                BEGIN
                    BEGIN
                        ALTER TABLE "ReservaPaymentSettings"
                            ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;
                    EXCEPTION
                        WHEN others THEN
                            NULL;
                    END;

                    IF pg_get_serial_sequence('"ReservaPaymentSettings"', 'Id') IS NOT NULL THEN
                        PERFORM setval(
                            pg_get_serial_sequence('"ReservaPaymentSettings"', 'Id'),
                            GREATEST((SELECT COALESCE(MAX("Id"), 1) FROM "ReservaPaymentSettings"), 1),
                            true
                        );
                    END IF;
                END $$;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
        }
    }
}
