using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ApartamentosRenta.Migrations
{
    /// <inheritdoc />
    public partial class EditableLeaseContract : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            if (migrationBuilder.ActiveProvider == "Npgsql.EntityFrameworkCore.PostgreSQL")
            {
                migrationBuilder.Sql("""
                    CREATE TABLE IF NOT EXISTS "LeaseContracts" (
                        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "Title" character varying(200) NOT NULL,
                        "Subtitle" character varying(200) NOT NULL,
                        "NoticeHtml" character varying(4000) NOT NULL,
                        "BodyHtml" text NOT NULL,
                        "UpdatedAt" timestamp with time zone NOT NULL
                    );

                    CREATE TABLE IF NOT EXISTS "ContractSubmissions" (
                        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "TenantName" character varying(120) NOT NULL,
                        "TenantEmail" character varying(256) NOT NULL,
                        "TenantPhone" character varying(30) NULL,
                        "SubmissionType" integer NOT NULL,
                        "SignatureImageData" bytea NULL,
                        "SignatureImageContentType" character varying(100) NULL,
                        "ProposedChanges" character varying(4000) NULL,
                        "SubmittedAt" timestamp with time zone NOT NULL
                    );

                    CREATE INDEX IF NOT EXISTS "IX_ContractSubmissions_SubmissionType" ON "ContractSubmissions" ("SubmissionType");
                    CREATE INDEX IF NOT EXISTS "IX_ContractSubmissions_SubmittedAt" ON "ContractSubmissions" ("SubmittedAt");
                    """);
                return;
            }

            migrationBuilder.CreateTable(
                name: "ContractSubmissions",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    TenantName = table.Column<string>(type: "TEXT", maxLength: 120, nullable: false),
                    TenantEmail = table.Column<string>(type: "TEXT", maxLength: 256, nullable: false),
                    TenantPhone = table.Column<string>(type: "TEXT", maxLength: 30, nullable: true),
                    SubmissionType = table.Column<int>(type: "INTEGER", nullable: false),
                    SignatureImageData = table.Column<byte[]>(type: "BLOB", nullable: true),
                    SignatureImageContentType = table.Column<string>(type: "TEXT", maxLength: 100, nullable: true),
                    ProposedChanges = table.Column<string>(type: "TEXT", maxLength: 4000, nullable: true),
                    SubmittedAt = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ContractSubmissions", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "LeaseContracts",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    Title = table.Column<string>(type: "TEXT", maxLength: 200, nullable: false),
                    Subtitle = table.Column<string>(type: "TEXT", maxLength: 200, nullable: false),
                    NoticeHtml = table.Column<string>(type: "TEXT", maxLength: 4000, nullable: false),
                    BodyHtml = table.Column<string>(type: "TEXT", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_LeaseContracts", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_ContractSubmissions_SubmissionType",
                table: "ContractSubmissions",
                column: "SubmissionType");

            migrationBuilder.CreateIndex(
                name: "IX_ContractSubmissions_SubmittedAt",
                table: "ContractSubmissions",
                column: "SubmittedAt");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ContractSubmissions");

            migrationBuilder.DropTable(
                name: "LeaseContracts");
        }
    }
}
