using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ApartamentosRenta.Migrations
{
    /// <inheritdoc />
    public partial class AddFurnitureCatalog : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            if (migrationBuilder.ActiveProvider == "Npgsql.EntityFrameworkCore.PostgreSQL")
            {
                migrationBuilder.Sql("""
                    CREATE TABLE IF NOT EXISTS "FurnitureCategories" (
                        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "Name" character varying(120) NOT NULL,
                        "Slug" character varying(140) NOT NULL,
                        "SortOrder" integer NOT NULL,
                        "IsActive" boolean NOT NULL
                    );
                    CREATE UNIQUE INDEX IF NOT EXISTS "IX_FurnitureCategories_Slug" ON "FurnitureCategories" ("Slug");
                    CREATE INDEX IF NOT EXISTS "IX_FurnitureCategories_IsActive" ON "FurnitureCategories" ("IsActive");
                    CREATE INDEX IF NOT EXISTS "IX_FurnitureCategories_SortOrder" ON "FurnitureCategories" ("SortOrder");

                    CREATE TABLE IF NOT EXISTS "FurnitureProducts" (
                        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "Title" character varying(200) NOT NULL,
                        "Slug" character varying(220) NOT NULL,
                        "Sku" character varying(80) NOT NULL,
                        "ShortDescription" character varying(300) NOT NULL,
                        "Description" character varying(8000) NOT NULL,
                        "Price" numeric(10,2) NOT NULL,
                        "CompareAtPrice" numeric(10,2) NULL,
                        "CategoryId" integer NOT NULL,
                        "IsActive" boolean NOT NULL,
                        "IsFeatured" boolean NOT NULL,
                        "CreatedAt" timestamp with time zone NOT NULL,
                        "UpdatedAt" timestamp with time zone NOT NULL,
                        CONSTRAINT "FK_FurnitureProducts_FurnitureCategories_CategoryId"
                            FOREIGN KEY ("CategoryId") REFERENCES "FurnitureCategories" ("Id") ON DELETE RESTRICT
                    );
                    CREATE UNIQUE INDEX IF NOT EXISTS "IX_FurnitureProducts_Slug" ON "FurnitureProducts" ("Slug");
                    CREATE INDEX IF NOT EXISTS "IX_FurnitureProducts_CategoryId" ON "FurnitureProducts" ("CategoryId");
                    CREATE INDEX IF NOT EXISTS "IX_FurnitureProducts_IsActive" ON "FurnitureProducts" ("IsActive");
                    CREATE INDEX IF NOT EXISTS "IX_FurnitureProducts_IsFeatured" ON "FurnitureProducts" ("IsFeatured");

                    CREATE TABLE IF NOT EXISTS "FurniturePhotos" (
                        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "ProductId" integer NOT NULL,
                        "Url" character varying(1000) NOT NULL,
                        "SortOrder" integer NOT NULL,
                        "IsPrimary" boolean NOT NULL,
                        CONSTRAINT "FK_FurniturePhotos_FurnitureProducts_ProductId"
                            FOREIGN KEY ("ProductId") REFERENCES "FurnitureProducts" ("Id") ON DELETE CASCADE
                    );
                    CREATE INDEX IF NOT EXISTS "IX_FurniturePhotos_ProductId" ON "FurniturePhotos" ("ProductId");
                    """);
                return;
            }

            migrationBuilder.CreateTable(
                name: "FurnitureCategories",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    Name = table.Column<string>(type: "TEXT", maxLength: 120, nullable: false),
                    Slug = table.Column<string>(type: "TEXT", maxLength: 140, nullable: false),
                    SortOrder = table.Column<int>(type: "INTEGER", nullable: false),
                    IsActive = table.Column<bool>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_FurnitureCategories", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "FurnitureProducts",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    Title = table.Column<string>(type: "TEXT", maxLength: 200, nullable: false),
                    Slug = table.Column<string>(type: "TEXT", maxLength: 220, nullable: false),
                    Sku = table.Column<string>(type: "TEXT", maxLength: 80, nullable: false),
                    ShortDescription = table.Column<string>(type: "TEXT", maxLength: 300, nullable: false),
                    Description = table.Column<string>(type: "TEXT", maxLength: 8000, nullable: false),
                    Price = table.Column<decimal>(type: "TEXT", precision: 10, scale: 2, nullable: false),
                    CompareAtPrice = table.Column<decimal>(type: "TEXT", precision: 10, scale: 2, nullable: true),
                    CategoryId = table.Column<int>(type: "INTEGER", nullable: false),
                    IsActive = table.Column<bool>(type: "INTEGER", nullable: false),
                    IsFeatured = table.Column<bool>(type: "INTEGER", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "TEXT", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_FurnitureProducts", x => x.Id);
                    table.ForeignKey(
                        name: "FK_FurnitureProducts_FurnitureCategories_CategoryId",
                        column: x => x.CategoryId,
                        principalTable: "FurnitureCategories",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "FurniturePhotos",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    ProductId = table.Column<int>(type: "INTEGER", nullable: false),
                    Url = table.Column<string>(type: "TEXT", maxLength: 1000, nullable: false),
                    SortOrder = table.Column<int>(type: "INTEGER", nullable: false),
                    IsPrimary = table.Column<bool>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_FurniturePhotos", x => x.Id);
                    table.ForeignKey(
                        name: "FK_FurniturePhotos_FurnitureProducts_ProductId",
                        column: x => x.ProductId,
                        principalTable: "FurnitureProducts",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_FurnitureCategories_IsActive",
                table: "FurnitureCategories",
                column: "IsActive");

            migrationBuilder.CreateIndex(
                name: "IX_FurnitureCategories_Slug",
                table: "FurnitureCategories",
                column: "Slug",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_FurnitureCategories_SortOrder",
                table: "FurnitureCategories",
                column: "SortOrder");

            migrationBuilder.CreateIndex(
                name: "IX_FurniturePhotos_ProductId",
                table: "FurniturePhotos",
                column: "ProductId");

            migrationBuilder.CreateIndex(
                name: "IX_FurnitureProducts_CategoryId",
                table: "FurnitureProducts",
                column: "CategoryId");

            migrationBuilder.CreateIndex(
                name: "IX_FurnitureProducts_IsActive",
                table: "FurnitureProducts",
                column: "IsActive");

            migrationBuilder.CreateIndex(
                name: "IX_FurnitureProducts_IsFeatured",
                table: "FurnitureProducts",
                column: "IsFeatured");

            migrationBuilder.CreateIndex(
                name: "IX_FurnitureProducts_Slug",
                table: "FurnitureProducts",
                column: "Slug",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            if (migrationBuilder.ActiveProvider == "Npgsql.EntityFrameworkCore.PostgreSQL")
            {
                migrationBuilder.Sql("""
                    DROP TABLE IF EXISTS "FurniturePhotos";
                    DROP TABLE IF EXISTS "FurnitureProducts";
                    DROP TABLE IF EXISTS "FurnitureCategories";
                    """);
                return;
            }

            migrationBuilder.DropTable(name: "FurniturePhotos");
            migrationBuilder.DropTable(name: "FurnitureProducts");
            migrationBuilder.DropTable(name: "FurnitureCategories");
        }
    }
}
