using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ApartamentosRenta.Migrations
{
    /// <inheritdoc />
    public partial class FixPostgresSchema : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            if (migrationBuilder.ActiveProvider is not "Npgsql.EntityFrameworkCore.PostgreSQL")
            {
                return;
            }

            migrationBuilder.Sql("""
                ALTER TABLE "Propiedades" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;
                ALTER TABLE "FotosPropiedad" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;
                ALTER TABLE "Citas" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;

                ALTER TABLE "Propiedades"
                    ALTER COLUMN "PrecioMensual" TYPE numeric(10,2) USING 0,
                    ALTER COLUMN "MetrosCuadrados" TYPE numeric(8,2) USING 0,
                    ALTER COLUMN "Disponible" TYPE boolean USING false,
                    ALTER COLUMN "FechaCreacion" TYPE timestamp with time zone USING NOW();

                ALTER TABLE "Citas"
                    ALTER COLUMN "FechaHora" TYPE timestamp with time zone USING NOW(),
                    ALTER COLUMN "FechaNacimiento" TYPE timestamp with time zone USING NOW(),
                    ALTER COLUMN "FechaSolicitud" TYPE timestamp with time zone USING NOW();
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
        }
    }
}
