using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ApartamentosRenta.Migrations
{
    /// <inheritdoc />
    public partial class FixAgentesPostgresSchema : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            if (migrationBuilder.ActiveProvider is not "Npgsql.EntityFrameworkCore.PostgreSQL")
            {
                return;
            }

            migrationBuilder.Sql("""
                DO $ef$
                BEGIN
                    IF EXISTS (
                        SELECT 1
                        FROM information_schema.tables
                        WHERE table_schema = 'public'
                          AND table_name = 'Agentes'
                    ) THEN
                        IF EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_schema = 'public'
                              AND table_name = 'Agentes'
                              AND column_name = 'Activo'
                              AND udt_name = 'int4'
                        ) THEN
                            ALTER TABLE "Agentes" ALTER COLUMN "Activo" TYPE boolean
                                USING ("Activo" <> 0);
                        END IF;

                        IF EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_schema = 'public'
                              AND table_name = 'Agentes'
                              AND column_name = 'Verificado'
                              AND udt_name = 'int4'
                        ) THEN
                            ALTER TABLE "Agentes" ALTER COLUMN "Verificado" TYPE boolean
                                USING ("Verificado" <> 0);
                        END IF;

                        ALTER TABLE "Agentes" ALTER COLUMN "Calificacion" TYPE numeric(3,2)
                            USING COALESCE("Calificacion"::numeric, 0);

                        ALTER TABLE "Agentes" ALTER COLUMN "TiempoRespuestaHoras" TYPE numeric(5,2)
                            USING COALESCE("TiempoRespuestaHoras"::numeric, 0);

                        ALTER TABLE "Agentes" ALTER COLUMN "FechaCreacion" TYPE timestamp with time zone
                            USING COALESCE("FechaCreacion"::timestamptz, NOW());

                        ALTER TABLE "Agentes" ALTER COLUMN "FechaActualizacion" TYPE timestamp with time zone
                            USING COALESCE("FechaActualizacion"::timestamptz, NOW());

                        ALTER TABLE "Agentes" ALTER COLUMN "FechaVerificacion" TYPE timestamp with time zone
                            USING "FechaVerificacion"::timestamptz;

                        IF NOT EXISTS (
                            SELECT 1
                            FROM pg_attribute a
                            JOIN pg_class c ON c.oid = a.attrelid
                            JOIN pg_namespace n ON n.oid = c.relnamespace
                            WHERE n.nspname = 'public'
                              AND c.relname = 'Agentes'
                              AND a.attname = 'Id'
                              AND a.attidentity IN ('a', 'd')
                        ) THEN
                            ALTER TABLE "Agentes"
                                ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;
                        END IF;

                        PERFORM setval(
                            pg_get_serial_sequence('"Agentes"', 'Id'),
                            GREATEST(COALESCE((SELECT MAX("Id") FROM "Agentes"), 0), 1),
                            (SELECT COUNT(*) > 0 FROM "Agentes")
                        );
                    END IF;
                END
                $ef$;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
        }
    }
}
