using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ApartamentosRenta.Migrations
{
    /// <inheritdoc />
    public partial class AddFurnitureColorCustomization : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            if (migrationBuilder.ActiveProvider == "Npgsql.EntityFrameworkCore.PostgreSQL")
            {
                migrationBuilder.Sql("""
                    ALTER TABLE "FurnitureProducts"
                    ADD COLUMN IF NOT EXISTS "AllowColorPreview" boolean NOT NULL DEFAULT true;

                    CREATE TABLE IF NOT EXISTS "FurnitureColorOptions" (
                        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "ProductId" integer NOT NULL,
                        "Name" character varying(80) NOT NULL,
                        "HexColor" character varying(16) NOT NULL,
                        "SortOrder" integer NOT NULL,
                        "IsDefault" boolean NOT NULL,
                        CONSTRAINT "FK_FurnitureColorOptions_FurnitureProducts_ProductId"
                            FOREIGN KEY ("ProductId") REFERENCES "FurnitureProducts" ("Id") ON DELETE CASCADE
                    );
                    CREATE INDEX IF NOT EXISTS "IX_FurnitureColorOptions_ProductId"
                        ON "FurnitureColorOptions" ("ProductId");

                    ALTER TABLE "FurniturePhotos"
                    ADD COLUMN IF NOT EXISTS "ColorOptionId" integer NULL;

                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1 FROM pg_constraint
                            WHERE conname = 'FK_FurniturePhotos_FurnitureColorOptions_ColorOptionId'
                        ) THEN
                            ALTER TABLE "FurniturePhotos"
                            ADD CONSTRAINT "FK_FurniturePhotos_FurnitureColorOptions_ColorOptionId"
                                FOREIGN KEY ("ColorOptionId") REFERENCES "FurnitureColorOptions" ("Id")
                                ON DELETE SET NULL;
                        END IF;
                    END $$;

                    CREATE INDEX IF NOT EXISTS "IX_FurniturePhotos_ColorOptionId"
                        ON "FurniturePhotos" ("ColorOptionId");
                    """);
                return;
            }

            migrationBuilder.AddColumn<bool>(
                name: "AllowColorPreview",
                table: "FurnitureProducts",
                type: "INTEGER",
                nullable: false,
                defaultValue: true);

            migrationBuilder.CreateTable(
                name: "FurnitureColorOptions",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    ProductId = table.Column<int>(type: "INTEGER", nullable: false),
                    Name = table.Column<string>(type: "TEXT", maxLength: 80, nullable: false),
                    HexColor = table.Column<string>(type: "TEXT", maxLength: 16, nullable: false),
                    SortOrder = table.Column<int>(type: "INTEGER", nullable: false),
                    IsDefault = table.Column<bool>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_FurnitureColorOptions", x => x.Id);
                    table.ForeignKey(
                        name: "FK_FurnitureColorOptions_FurnitureProducts_ProductId",
                        column: x => x.ProductId,
                        principalTable: "FurnitureProducts",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.AddColumn<int>(
                name: "ColorOptionId",
                table: "FurniturePhotos",
                type: "INTEGER",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_FurniturePhotos_ColorOptionId",
                table: "FurniturePhotos",
                column: "ColorOptionId");

            migrationBuilder.CreateIndex(
                name: "IX_FurnitureColorOptions_ProductId",
                table: "FurnitureColorOptions",
                column: "ProductId");

            migrationBuilder.AddForeignKey(
                name: "FK_FurniturePhotos_FurnitureColorOptions_ColorOptionId",
                table: "FurniturePhotos",
                column: "ColorOptionId",
                principalTable: "FurnitureColorOptions",
                principalColumn: "Id",
                onDelete: ReferentialAction.SetNull);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            if (migrationBuilder.ActiveProvider == "Npgsql.EntityFrameworkCore.PostgreSQL")
            {
                migrationBuilder.Sql("""
                    ALTER TABLE "FurniturePhotos"
                    DROP CONSTRAINT IF EXISTS "FK_FurniturePhotos_FurnitureColorOptions_ColorOptionId";
                    DROP INDEX IF EXISTS "IX_FurniturePhotos_ColorOptionId";
                    ALTER TABLE "FurniturePhotos" DROP COLUMN IF EXISTS "ColorOptionId";
                    DROP TABLE IF EXISTS "FurnitureColorOptions";
                    ALTER TABLE "FurnitureProducts" DROP COLUMN IF EXISTS "AllowColorPreview";
                    """);
                return;
            }

            migrationBuilder.DropForeignKey(
                name: "FK_FurniturePhotos_FurnitureColorOptions_ColorOptionId",
                table: "FurniturePhotos");

            migrationBuilder.DropTable(
                name: "FurnitureColorOptions");

            migrationBuilder.DropIndex(
                name: "IX_FurniturePhotos_ColorOptionId",
                table: "FurniturePhotos");

            migrationBuilder.DropColumn(
                name: "AllowColorPreview",
                table: "FurnitureProducts");

            migrationBuilder.DropColumn(
                name: "ColorOptionId",
                table: "FurniturePhotos");
        }
    }
}
